import React, { useState } from 'react';
import Card from './ui/Card';
import { ChevronDownIcon, ChevronUpIcon } from './ui/Icons';

const faqs = [
  {
    question: "What is a carbon footprint?",
    answer: "A carbon footprint is the total amount of greenhouse gases (including carbon dioxide and methane) that are generated by our actions. It's measured in tons of CO2 equivalent (tCO₂e)."
  },
  {
    question: "Why is tracking my carbon footprint important?",
    answer: "Tracking your footprint helps you understand your personal impact on the environment. It's the first step to identifying areas where you can make changes to live more sustainably and contribute to combating climate change."
  },
  {
    question: "How does Enviro-Lytix calculate emissions?",
    answer: "We use standardized emission factors from reputable sources for common activities like transportation, energy use, and diet. While it's an estimation, it provides a strong baseline for understanding and reducing your impact."
  },
  {
    question: "What are some simple ways to reduce my footprint?",
    answer: "Small changes can make a big difference! Consider reducing meat consumption, switching to energy-efficient appliances, using public transport or cycling, and being mindful of your purchases (avoiding fast fashion and single-use products)."
  }
];

const FAQItem: React.FC<{ faq: { question: string, answer: string } }> = ({ faq }) => {
    const [isOpen, setIsOpen] = useState(false);
    return (
        <div className="border-b border-slate-200 dark:border-slate-700 py-4">
            <button onClick={() => setIsOpen(!isOpen)} className="w-full flex justify-between items-center text-left group">
                <h3 className="text-lg font-semibold text-slate-800 dark:text-slate-200 group-hover:text-emerald-600 dark:group-hover:text-emerald-400 transition-colors">{faq.question}</h3>
                {isOpen ? <ChevronUpIcon className="h-6 w-6 text-emerald-600" /> : <ChevronDownIcon className="h-6 w-6 text-slate-500 group-hover:text-emerald-600 dark:group-hover:text-emerald-400 transition-colors" />}
            </button>
            {isOpen && (
                <p className="mt-2 text-slate-600 dark:text-slate-400 pr-6">
                    {faq.answer}
                </p>
            )}
        </div>
    );
};

const Resources: React.FC = () => {
  return (
    <div className="max-w-4xl mx-auto">
      <div className="text-center mb-8">
        <h1 className="text-4xl font-bold">About & Vision</h1>
        <p className="text-slate-500 dark:text-slate-400 mt-1">Learn more about carbon footprints and our mission.</p>
      </div>
      
      <div className="space-y-8">
        <Card>
          <h2 className="text-2xl font-bold text-emerald-600 dark:text-emerald-400 mb-4">Our Mission</h2>
          <img 
            src="https://img.freepik.com/premium-photo/pollution-prevention_693425-31605.jpg" 
            alt="A lush forest with solar panels" 
            className="w-full h-66 object-cover rounded-xl my-4 shadow-lg"
          />
          <p className="text-slate-700 dark:text-slate-300 leading-relaxed">
            At Enviro-Lytix, our mission is to empower individuals to take meaningful climate action. We believe that by "Making Carbon Visible," we can provide the awareness and tools necessary for people to understand their environmental impact. Through real-time tracking, AI-powered insights, and personalized recommendations, we aim to make sustainable living accessible, engaging, and impactful for everyone.
          </p>
          <p className="mt-4 text-slate-700 dark:text-slate-300 leading-relaxed">
            Because every action leaves a mark, and together, we can ensure that mark is a positive one for our planet.
          </p>
        </Card>
        
        <Card>
          <h2 className="text-2xl font-bold text-emerald-600 dark:text-emerald-400 mb-4">Frequently Asked Questions</h2>
          <div className="space-y-2">
            {faqs.map((faq, index) => (
              <FAQItem key={index} faq={faq} />
            ))}
          </div>
        </Card>
      </div>
    </div>
  );
};

export default Resources;